// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUE7gtlcF0-zP2msfo4uMmEP4YVFWs0pM',
    appId: '1:463214715157:web:a0878ee6f368e6fbfa091c',
    messagingSenderId: '463214715157',
    projectId: 'superb-joy-447518-c4',
    authDomain: 'superb-joy-447518-c4.firebaseapp.com',
    storageBucket: 'superb-joy-447518-c4.firebasestorage.app',
    measurementId: 'G-3DQZWVBVS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEmKMJvkJ_yfb6nUcDffwtR23z499h99E',
    appId: '1:463214715157:android:c9b039a122492015fa091c',
    messagingSenderId: '463214715157',
    projectId: 'superb-joy-447518-c4',
    storageBucket: 'superb-joy-447518-c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfRQlRLywNDrSO-0Ybh8ilcN-lEkIzBks',
    appId: '1:463214715157:ios:ec17ebc81dc28ceafa091c',
    messagingSenderId: '463214715157',
    projectId: 'superb-joy-447518-c4',
    storageBucket: 'superb-joy-447518-c4.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfRQlRLywNDrSO-0Ybh8ilcN-lEkIzBks',
    appId: '1:463214715157:ios:ec17ebc81dc28ceafa091c',
    messagingSenderId: '463214715157',
    projectId: 'superb-joy-447518-c4',
    storageBucket: 'superb-joy-447518-c4.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUE7gtlcF0-zP2msfo4uMmEP4YVFWs0pM',
    appId: '1:463214715157:web:17c1e527ec7d3a81fa091c',
    messagingSenderId: '463214715157',
    projectId: 'superb-joy-447518-c4',
    authDomain: 'superb-joy-447518-c4.firebaseapp.com',
    storageBucket: 'superb-joy-447518-c4.firebasestorage.app',
    measurementId: 'G-BS29DTC25R',
  );
}
